name: Deploy .NET app to Azure Web App

on:
  push:
    branches:
      - master  # o tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Set up .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # O la versión que estés usando

    - name: 'Restore dependencies'
      run: dotnet restore

    - name: 'Build app'
      run: dotnet build --configuration Release

    - name: 'Publish app'
      run: dotnet publish --configuration Release --output ./publish

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: <YOUR_A_
